apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-prod
        version: prod
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "frontend-prod"
        - name: UPSTREAM_URI
          value: "http://middleware/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
        version: prod
    spec:
      containers:
      - name: middleware
        image: gcr.io/<PROJECT_ID>/istiotest:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "middleware-prod"
        - name: UPSTREAM_URI
          value: "http://backend/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
        version: canary
    spec:
      containers:
      - name: middleware
        image: gcr.io/<PROJECT_ID>/istiotest:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "middleware-canary"
        - name: UPSTREAM_URI
          value: "http://backend/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: prod
    spec:
      containers:
      - name: backend
        image: gcr.io/<PROJECT_ID>/istiotest:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: "backend-prod"
        - name: UPSTREAM_URI
          value: "http://worldclockapi.com/api/json/utc/now"
