# Generated by Django 2.2.1 on 2019-05-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, upload_to='objects/'),
        ),
    ]
